pipeline {
    agent any

    stages {
        stage('Checkout branch') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/sp-a-in/test.git'
            }
        }
        stage('Build the image') {
            steps {
                sh "cd mysite"
                sh "ls"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}