pipeline {
    agent any

    stages {
        stage('Checkout branch') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/sp-a-in/test.git'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}